site_name: Konstantinos N. Plataniotis
site_url: https://platanio.github.io

nav:
  - Home: index.md
  - Info: info.md

theme:
  name: material
  language: en
  palette:
    primary: green
    accent: light-green
  favicon: assets/images/favicon/favicon.ico
  logo: assets/images/logo/uoft.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top



extra:
  consent:
    title: "This website uses cookies"
    description: "We use cookies to recognize your repeated visits and preferences, as well
    as to measure the effectiveness of our documentation and whether users
    find what they're searching for. With your consent, you're helping us to
    make our documentation better."
    actions:
      - accept
      - manage

copyright: >
  Copyright &copy; 2023 Konstantinos N. Plataniotis –
  <a href="#__consent">Change cookie settings</a>



